# Provides DAWN_SOURCES_DIR, DAWN_SOURCES, DAWN_INCLUDE_DIRS

set(DAWN_SOURCES_DIR ${CMAKE_CURRENT_LIST_DIR})

set(DAWN_SOURCES
    ${DAWN_SOURCES_DIR}/dawn.c
)


set(DAWN_INCLUDE_DIRS ${SHARED_SOURCES_DIR})


